name: CI and Doc build

on:
  page_build:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: leanprover/lean-action@v1
      - id: restore_doc
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/docs/.lake
          key: doc-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('docs/lake-manifest.json') }}-${{ github.sha }}
          restore-keys: doc-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('docs/lake-manifest.json') }}
      - name: Build docs
        id: build_doc
        if: ${{ github.ref_name == 'main' && steps.restore_doc.outputs.cache-hit != 'true' }}
        working-directory: ${{ github.workspace }}/docs
        run: |
          lake update
          lake build Lean4Gists:docs
      - uses: actions/cache/save@v4
        if: ${{ steps.restore_doc.outputs.cache-hit != 'true' }}
        with:
          path: ${{ github.workspace }}/docs/.lake
          key: ${{ steps.restore_doc.outputs.cache-primary-key }}
      - name: Package docs as artifact
        if: ${{ steps.build_doc.outcome == 'success' }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ github.workspace }}/docs/.lake/build/doc/
  deploy:
    if: ${{ github.ref_name == 'main' }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

